name: Worldmeter Data
on: 
   schedule:
       - cron: '0 * * * *'
jobs:
  fetchstatedata:
    runs-on: ubuntu-latest
    name: Fetch World Data
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Install conda environment
        uses: conda-incubator/setup-miniconda@v1
        with:
          activate-environment: jupyter-actions
          environment-file: environment.yml
          python-version: 3.7
          
      - name: Run Script
        run: |
          conda activate jupyter-actions
          pytest
          python Worldometer Web scraping.ipynb
      - name: Commit Report
        continue-on-error: true
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -A
          git commit -am "Automatically Updated World Data"
          git push
